### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by ghost** [nkhoit/dcss.py#4]
We should be logging a lot more stuff. Most notably, we should have a verbose log which contains every communication from the server, and also contains a list of 'unsupported' escape sequences that are being ignored by TerminalBuffer

**Comment by nkhoit** [comment]
Probably just use the logging module like these kids: https://github.com/Rapptz/discord.py/blob/89eb3392afbb25df8a59e6bdd61531e90e48bbb8/docs/logging.rst

**Comment by ghost** [comment]
Added appropriate logging for all previous code, and logging moving forwards should be easy to keep up with. marking this as complete.
